# MCP Orchestrator - Hybrid Deployment (Recommended)
# Database: Docker PostgreSQL (isolated and reliable)
# Backend: Native installation (optimal MCP server compatibility) 
# Frontend: Docker container (consistent environment)
# Monitoring: Separate docker-compose.monitoring.yml

version: '3.8'

services:
  # PostgreSQL Database - Core infrastructure
  postgresql:
    image: postgres:15
    container_name: mcp-orch-postgres
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./configs/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=${DB_USER:-mcp_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-mcp_password}
      - POSTGRES_DB=${DB_NAME:-mcp_orch}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-mcp_user} -d ${DB_NAME:-mcp_orch}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Frontend Web Interface
  frontend:
    build:
      context: ./web
      dockerfile: ../Dockerfile.frontend
      args:
        - NEXT_PUBLIC_MCP_API_URL=${NEXT_PUBLIC_MCP_API_URL:-http://localhost:8000}
    container_name: mcp-orch-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NEXTAUTH_URL=http://localhost:${FRONTEND_PORT:-3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-secret-key-here}
      - NEXT_PUBLIC_MCP_API_URL=${NEXT_PUBLIC_MCP_API_URL:-http://localhost:8000}
    restart: unless-stopped
    profiles:
      - frontend

  # Redis for session store (Optional - Enterprise)
  redis:
    image: redis:7-alpine
    container_name: mcp-orch-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - enterprise

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local

# Usage Examples:
# 
# Quick Start (Database only - Backend runs natively):
# docker-compose -f docker-compose.hybrid.yml up -d postgresql
# uv run mcp-orch serve
#
# Standard (Database + Frontend):  
# docker-compose -f docker-compose.hybrid.yml --profile frontend up -d
# uv run mcp-orch serve
#
# With Monitoring (add monitoring stack):
# docker-compose -f docker-compose.hybrid.yml --profile frontend up -d
# docker-compose -f docker-compose.monitoring.yml up -d
# uv run mcp-orch serve
#
# Enterprise (with Redis):
# docker-compose -f docker-compose.hybrid.yml --profile frontend --profile enterprise up -d